#
# Support
#
consul:
  command: -server -bootstrap
  image: progrium/consul:latest
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

registrator:
  command: -ip=192.168.99.100 consul://consul:8500
  image: gliderlabs/registrator:latest
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - consul

lb:
  build: ./docker/lb
  links:
    - consul
  ports:
    - "80:80"
  environment:
    CONSUL_URL: consul:8500
  volumes:
    - ./docker/lb/consul-template:/etc/consul-template

#
# Services
#
frontendwww:
  image: nginx:1.10.1
  volumes:
    - ./docker/php/nginx/conf.d:/etc/nginx/conf.d
    - ./var/frontendwww/error/:/var/log/nginx
  volumes_from:
    - frontendphp
  links:
    - frontendphp:php
  ports:
    - "8080"
  environment:
    SERVICE_NAME: frontend
    SERVICE_TAGS: production
frontendphp:
  build: ./docker/php/dev
  volumes:
    - ./services/frontend/:/var/www/html/